catalogo/catalogo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name="inicio"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.logout_then_login, name="logout"),

    # Includes
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuarios.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/productos/urls.py
from django.urls import path

from . import views

app_name="productos"

urlpatterns = [
    path('admin/listado/', views.AdminListadoProductos.as_view(), name="admin_listado_productos"),
    # path('admin/nuevo/<int:pk>/', views.NuevoProducto.as_view(), name="admin_nuevo_producto"),
    path('admin/nuevo/', views.NuevoProducto.as_view(), name="admin_nuevo_producto"),
    path('admin/editar/<int:pk>/', views.EditarProducto.as_view(), name="editar"),
    path('me-gusta/<int:id_producto>/', views.dar_me_gusta, name="dar_me_gusta")
]

catalogo/usuarios/urls.py
from django.urls import path

from . import views

app_name="usuarios"

urlpatterns = [
    path('registro/', views.Registro.as_view(), name="registro"),
]

catalogo/categorias/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)


    def __str__(self):
        return self.nombre

catalogo/productos/models.py
from django.db import models

from categorias.models import Categoria
from usuarios.models import Usuario

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    descripcion = models.TextField()

    activo = models.BooleanField(default=True)

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, related_name="categorias", blank=True)

    categoria2 = models.ManyToManyField(Categoria)

    imagen = models.ImageField(upload_to="productos", null=True, blank=True)
    # models.FileField
    # models.BinaryField

    # ficha = models.OneToOneField(Ficha)

    usuario =  models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name="productos", blank=True)

    def __str__(self):
        return self.nombre


class MeGusta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

"""
class ProductoCategoria(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    # fecha
"""

catalogo/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    es_administrador = models.BooleanField(default=False)

catalogo/productos/forms.py
from django import forms

from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields=["nombre", "descripcion", "precio", "activo", "imagen", "categoria", "categoria2"]
    
    def clean_precio(self):
        precio = self.cleaned_data["precio"]
        if precio <= 0:
            raise forms.ValidationError("El precio debe ser un numero positivo")
        return precio 

catalogo/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


from .models import Usuario

class UsuarioForm(UserCreationForm):
    first_name = forms.CharField(label="Nombre", widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(label="Apellido", widget=forms.TextInput(attrs={"class": "form-control"}))
    
    class Meta:
        model=Usuario
        fields=["first_name", "last_name", "email", "username", "password1", "password2"]

catalogo/catalogo/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required



from productos.models import Producto

from utils.mixins import is_admin_required

@is_admin_required()
def inicio(request):
    template_name = "index.html"
    
    # ===============================
    # query en django utilizando el orm
    """
    p = Producto.objects.create(
        nombre="Pantalon",
        precio=2000,
        descripcion="Pantalon azul"
    )
    """

    contexto = {
        'productos': Producto.objects.filter(activo=True)
    }
    return render(request, template_name, contexto)

"""
def login(request):
    if 'btn_ingresar'in request.GET:
        username = request.GET.get("username")
    
    return render(request, "login.html", {})    
"""    

catalogo/categorias/views.py
from django.shortcuts import render

# Create your views here.

catalogo/productos/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

from utils.mixins import IsAdminMixin

from .forms import ProductoForm
from .models import Producto, MeGusta

"""
def admin_listado_productos(request):
    template_name = "productos/listado.html"

    contexto = {
        'productos': Producto.objects.all()
    }
    return render(request, template_name, contexto)
"""

class AdminListadoProductos(LoginRequiredMixin, IsAdminMixin, ListView):
    template_name = "productos/listado.html"
    model = Producto
    context_object_name = "productos"
    paginate_by = 20

    def get_queryset(self):
        productos = Producto.objects.all()
        nombre_producto = self.request.GET.get("buscador")
        if nombre_producto:
            productos = productos.filter(nombre__contains=nombre_producto)

        return productos.order_by("nombre")


class NuevoProducto(CreateView):
    model = Producto 
    template_name = "productos/nuevo_producto.html"
    form_class = ProductoForm

    def get_success_url(self):
        return reverse("productos:admin_listado_productos")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["producto"] = Producto.objects.get(id=3) 
        return context

    def form_valid(self, form):
        f = form.save(commit=False)
        f.usuario_id = self.request.user.id
        return super(NuevoProducto, self).form_valid(form)



class EditarProducto(UpdateView):   
    model = Producto 
    template_name = "productos/editar.html"
    form_class = ProductoForm     

    def get_success_url(self):
        return reverse("productos:admin_listado_productos")


def dar_me_gusta(request, id_producto):
    mg = MeGusta.objects.filter(usuario=request.user, producto__id=id_producto)
    if not mg:
        mg = MeGusta.objects.create(usuario=request.user, producto=Producto.objects.get(id=id_producto))
    return HttpResponseRedirect(reverse("inicio"))

catalogo/usuarios/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse

from .forms import UsuarioForm
from .models import Usuario

class Registro(CreateView):
    model = Usuario 
    template_name = "usuarios/registro.html"
    form_class = UsuarioForm

    def get_success_url(self):
        return reverse("login")

catalogo/templates/base/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Sitio de Catalogo de Productos</title>

        <!-- Css -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block css_extras %}
          
        {% endblock css_extras %}
          
    </head>
    <body>
    
        <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white">Follow on Twitter</a></li>
                    <li><a href="#" class="text-white">Like on Facebook</a></li>
                    <li><a href="#" class="text-white">Email me</a></li>
                </ul>
                </div>
            </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
                <strong>SITIO DE COMPRAS</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            </div>
        </div>
        </header>

        <main>

        <section id="seccion_index" class="py-5 text-center container">
            <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">CATALOGO DE PRODUCTOS</h1>
                <p class="lead text-muted">El mejor sitio para hacer tus compras.</p>
                <p>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="btn btn-primary my-2">Cerrar sesion</a> 
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary my-2">Iniciar sesion</a>
                        <a href="#" class="btn btn-secondary my-2">Registrarme</a>
                    {% endif %}
                        

                </p>
            </div>
            </div>
        </section>

        <div class="album py-5 bg-light">
            <div class="container">
                
                {% if user.is_authenticated %}
                  
                
                  
                  <div class="row">
                    <p>Hola {{user.username}}!</p>
                  </div>
                {% endif %}
                <div class="row">
                    <nav class="navbar navbar-expand-lg bg-light">
                        <div class="container-fluid">
                          <a class="navbar-brand" href="#">Sitio de compras</a>
                          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                          </button>
                          <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                              <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                              </li>
                              
                              {% if user.es_administrador %}
                                
                              
                                
                                <li class="nav-item">
                                  <a class="nav-link" href="{% url 'productos:admin_listado_productos' %}">Productos</a>
                                </li>
                              {% endif %}
                              <!--
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  Dropdown
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="#">Action</a></li>
                                  <li><a class="dropdown-item" href="#">Another action</a></li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                              </li>

                              <li class="nav-item">
                                <a class="nav-link disabled">Disabled</a>
                              </li>
                              -->
                            </ul>
                            <form class="d-flex" role="search" method="get">
                              <input class="form-control me-2" type="search" placeholder="Buscar productos" aria-label="Search" name="buscador">
                              <button class="btn btn-outline-success" type="submit">Search</button>
                            </form>
                          </div>
                        </div>
                      </nav>
                </div>


                
                {% block contenido %}
                    
                {% endblock contenido %}
                    
                


            </div>
        </div>

        </main>

        <footer class="text-muted py-5">
        <div class="container">
            <p class="float-end mb-1">
            <a href="#">Back to top</a>
            </p>
            <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
            <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.2/getting-started/introduction/">getting started guide</a>.</p>
        </div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

        {% block js_extras %}
          
        {% endblock js_extras %}
    </body>
</html>

catalogo/templates/includes/errores_form.html
{% if form.errors %}
            
    {% for field in form %}
        
        {% for error in field.errors  %}
            <div class="alert alert-danger" role="alert">
                {{field.label}}: {{error|safe}}
            </div>
            
        {% endfor %}
            
        
    {% endfor %}

    
    {% for error in form.non_field_errors  %}
        <div class="alert alert-danger" role="alert">
            {{error|safe}}
        </div>
    {% endfor %}
        
        
{% endif %}

catalogo/templates/includes/paginado.html
{% if is_paginated %}
	<nav>
	  	<ul class="pagination pagination-circle mg-b-0 justify-content-center">
		  	{% if page_obj.number == 1  %}
		  		<li class="page-item disabled"><a class="page-link">primera</a></li>
		  	{% else %}
		  		<li class="page-item"><a class="page-link" href="?page=1">primera</a></li>
	         {% endif %}
		  	
		  	
		  	{% if page_obj.has_previous %}
		  		<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">anterior</a></li>
		  	{% else %}
		  		<li class="page-item disabled"><a class="page-link">anterior</a></li>
		  	{% endif %}

		  	{% for i in paginator.page_range %}
		  		{% if page_obj.number|add:'-1' <= i and page_obj.number|add:'1' >= i %}
	            	<li class="page-item {% if page_obj.number == i %}active{% endif %}"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
	            {% else %}

	        	{% endif %}
	        {% endfor %}
		  	
	        {% if page_obj.has_next %}
		    	<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a></li>
		    {% else %}
		    	<li class="page-item disabled"><a class="page-link">siguiente</a></li>
		    {% endif %}

		    {% if page_obj.number == paginator.num_pages %}
		    	<li class="page-item disabled"><a class="page-link">ultima</a></li>
		    {% else %}
		    	<li class="page-item"><a class="page-link" href="?page={{paginator.num_pages}}">ultima</a></li>
		    {% endif %}  
	  	</ul>
	</nav>
	
{% endif %}

catalogo/templates/index.html
{% extends 'base/base.html' %}

{% block contenido %}    
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        
        {% for p in productos %}
            <div class="col">
                <div class="card shadow-sm">
                    
                    {% if p.imagen %}
                        <img src="{{p.imagen.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225">
                    {% else %}
                        <svg  xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Sin imagen</text></svg>
                    {% endif %}
                        
                    

                    <div class="card-body">
                        <h5 class="card-title">{{p.nombre}} <span class="badge bg-secondary">${{p.precio}}</span><span class="badge rounded-pill text-bg-info">{{p.categoria.nombre}}</span>
                        </h5>
                        <p class="card-text">{{p.descripcion}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                
                                {% for c in p.categoria2.all %}
                                    <span class="badge rounded-pill text-bg-info">{{c.nombre}}</span>
                                {% endfor %}
                                    

                            </div>
                            <small class="text-muted"><a type="button" class="btn btn-success" href="{% url 'productos:dar_me_gusta' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
                              </svg></a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="row">
                <div class="col">
                    <div class="alert alert-success" role="alert">
                        <h4 class="alert-heading">Sin productos</h4>
                        <p>Aun no se han cargado productos.</p>
                        <hr>
                        <p class="mb-0">Por favor ingresa mas adelante.</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock contenido %}

catalogo/templates/login.html
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="generator" content="Hugo 0.104.2">
        <title>Signin Template · Bootstrap v5.2</title>


        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    </head>
    <body class="text-center">
    
        <main class="form-signin w-100 m-auto">
            <form method="post">{% csrf_token %}
                <img class="mb-4" src="https://cdn-icons-png.flaticon.com/512/3486/3486578.png" alt="" width="72" height="57">
                <h1 class="h3 mb-3 fw-normal">Ingrese a nuestro sitio</h1>
                

                {% include 'includes/errores_form.html' %}


                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
                    <label for="floatingInput">Nombre de Usuario</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                    <label for="floatingPassword">Contraseña</label>
                </div>

                <br>
                <p><button class="w-100 btn btn-lg btn-primary" type="submit" name="btn_ingresar">INGRESAR</button></p>
                <p><a class="w-100 btn btn-lg btn-primary" href="{% url 'inicio' %}">VOLVER Al INICIO</a></p>
                <a class="w-100 btn btn-lg btn-primary" href="{% url 'usuarios:registro' %}">REGISTRARME</a>
            </form>
        </main>

    </body>
</html>

catalogo/templates/productos/editar.html
{% extends 'base/base.html' %}

{% block contenido %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}

        <p><button class="w-100 btn btn-lg btn-primary" type="submit" name="btn_ingresar">GUARDAR</button></p>
        <p><a href="{% url 'productos:admin_listado_productos' %}" class="w-100 btn btn-lg btn-primary">Cancelar</a></p>
    </form>
{% endblock contenido %}

catalogo/templates/productos/listado.html
{% extends 'base/base.html' %}

{% block contenido %}
<div class="row">
    <div class="col">
        <a type="button" class="btn btn-success" href="{% url 'productos:admin_nuevo_producto' %}">NUEVO PRODUCTO</a>
    </div>
</div><br>
<div class="card">
    <div class="card-header">
        Lista de productos
    </div>
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre Producto</th>
                    <th scope="col">Precio</th>
                    <th>Categoria</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>

                {% for p in productos %}
                    <tr>
                        <th scope="row">{{p.id}}</th>
                        <td>{{p.nombre}}</td>
                        <td>${{p.precio}}</td>
                        <td>
                        {% for c in p.categoria2.all  %}
                            {{c.id}}
                        {% endfor %}
                        </td>
                        <td>
                            <a href="{% url 'productos:editar' p.id %}" class="btn btn-warning">Editar</a>
                            <button type="button" class="btn btn-danger">Eliminar</button>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% include 'includes/paginado.html' %}
    </div>
</div>


{% endblock contenido %}

catalogo/templates/productos/nuevo_producto.html
{% extends 'base/base.html' %}

{% block contenido %}
    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}

        <p><button class="w-100 btn btn-lg btn-primary" type="submit" name="btn_ingresar">CREAR</button></p>
    </form>
{% endblock contenido %}

catalogo/templates/usuarios/registro.html
{% extends 'base/base.html' %}

{% block contenido %}    
    <div class="card">
        <div class="card-body">
            <form method="post">{% csrf_token %}
                {{form.as_p}}

                <button type="submit" class="btn btn-primary">Crear</button>
            </form>
        </div>
    </div>
{% endblock contenido %}